/*
* generated by Xtext
*/
package com.puppetlabs.geppetto.module.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ModuleUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.puppetlabs.geppetto.module.dsl.ui.internal.ModuleActivator.getInstance().getInjector("com.puppetlabs.geppetto.module.dsl.Module");
	}
	
}
