/**
 * Copyright (c) 2013 Puppet Labs, Inc. and other contributors, as listed below.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Puppet Labs
 *
 */
package com.puppetlabs.geppetto.ruby.spi;

import com.google.inject.Inject;
import com.google.inject.name.Named;

/**
 * Ruby parser configuration
 */
public class RubyParserConfiguration {
	public static enum RubyVersion {
		V1_8, V1_9, V2_0
	}

	public static final String COLLECT_WARNINGS = "rubyParser.collectWarnings";

	private final RubyVersion rubyVersion;;

	private final boolean collectWarnings;

	@Inject
	public RubyParserConfiguration(RubyVersion rubyVersion, @Named(COLLECT_WARNINGS) Boolean collectWarnings) {
		this.rubyVersion = rubyVersion;
		this.collectWarnings = collectWarnings;
	}

	/**
	 * @return The parser version to use
	 */
	public RubyVersion getVersion() {
		return rubyVersion;
	}

	/**
	 * @return wether or not to collect warnings generated by the parser
	 */
	public boolean isCollectWarnings() {
		return collectWarnings;
	}
}
