/**
 * generated by Xtext
 */
package com.puppetlabs.geppetto.module.dsl.ui.labeling;

import com.google.inject.Inject;
import com.puppetlabs.geppetto.module.dsl.ModuleUtil;
import com.puppetlabs.geppetto.module.dsl.metadata.JsonArray;
import com.puppetlabs.geppetto.module.dsl.metadata.JsonDependency;
import com.puppetlabs.geppetto.module.dsl.metadata.JsonMetadata;
import com.puppetlabs.geppetto.module.dsl.metadata.JsonObject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.eclipse.xtext.util.Strings;
import org.eclipse.xtext.xbase.lib.Extension;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class ModuleLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  @Extension
  private ModuleUtil _moduleUtil;
  
  @Inject
  public ModuleLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final JsonArray array) {
    return "[]";
  }
  
  public String text(final JsonObject obj) {
    return "{}";
  }
  
  public Object text(final JsonDependency dependency) {
    Object _xifexpression = null;
    boolean _isResolved = this._moduleUtil.isResolved(dependency);
    if (_isResolved) {
      JsonMetadata _referencedModule = this._moduleUtil.getReferencedModule(dependency);
      _xifexpression = this.text(_referencedModule);
    } else {
      JsonMetadata _referencedModule_1 = this._moduleUtil.getReferencedModule(dependency);
      _xifexpression = this._moduleUtil.getName(_referencedModule_1);
    }
    return _xifexpression;
  }
  
  public String text(final JsonMetadata metadata) {
    String _xblockexpression = null;
    {
      String desc = this._moduleUtil.getString(metadata, "description");
      boolean _isEmpty = Strings.isEmpty(desc);
      if (_isEmpty) {
        String _string = this._moduleUtil.getString(metadata, "summary");
        desc = _string;
        boolean _isEmpty_1 = Strings.isEmpty(desc);
        if (_isEmpty_1) {
          String _string_1 = this._moduleUtil.getString(metadata, "name");
          desc = _string_1;
        }
      }
      _xblockexpression = desc;
    }
    return _xblockexpression;
  }
  
  public String image(final JsonDependency dependency) {
    return "obj16/puppet-16.png";
  }
  
  public String image(final JsonMetadata metadata) {
    return "obj16/puppet-16.png";
  }
}
