/*
 * generated by Xtext
 */
package com.puppetlabs.geppetto.module.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.puppetlabs.geppetto.module.dsl.ui.internal.ModuleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ModuleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ModuleActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ModuleActivator.getInstance().getInjector(ModuleActivator.COM_PUPPETLABS_GEPPETTO_MODULE_DSL_MODULE);
	}
	
}
