/*
 * generated by Xtext
 */
package com.puppetlabs.geppetto.module.dsl.ui.internal;

import java.util.Collections;
import java.util.Map;

import org.apache.log4j.Logger;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.shared.SharedStateModule;
import org.eclipse.xtext.util.Modules2;
import org.osgi.framework.BundleContext;

import com.google.common.collect.Maps;
import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class ModuleActivator extends AbstractUIPlugin {

	public static String getId() {
		return getInstance().getBundle().getSymbolicName();
	}

	public static ModuleActivator getInstance() {
		return INSTANCE;
	}

	public static final String COM_PUPPETLABS_GEPPETTO_MODULE_DSL_MODULE = "com.puppetlabs.geppetto.module.dsl.Module";

	private static final Logger logger = Logger.getLogger(ModuleActivator.class);

	private static ModuleActivator INSTANCE;

	private Map<String, Injector> injectors = Collections.synchronizedMap(Maps.<String, Injector> newHashMapWithExpectedSize(1));

	protected Injector createInjector(String language) {
		try {
			Module runtimeModule = getRuntimeModule(language);
			Module sharedStateModule = getSharedStateModule();
			Module uiModule = getUiModule(language);
			Module mergedModule = Modules2.mixin(runtimeModule, sharedStateModule, uiModule);
			return Guice.createInjector(mergedModule);
		}
		catch(Exception e) {
			logger.error("Failed to create injector for " + language);
			logger.error(e.getMessage(), e);
			throw new RuntimeException("Failed to create injector for " + language, e);
		}
	}

	public Injector getInjector(String language) {
		synchronized(injectors) {
			Injector injector = injectors.get(language);
			if(injector == null) {
				injectors.put(language, injector = createInjector(language));
			}
			return injector;
		}
	}

	protected Module getRuntimeModule(String grammar) {
		if(COM_PUPPETLABS_GEPPETTO_MODULE_DSL_MODULE.equals(grammar)) {
			return new com.puppetlabs.geppetto.module.dsl.ModuleRuntimeModule();
		}

		throw new IllegalArgumentException(grammar);
	}

	protected Module getSharedStateModule() {
		return new SharedStateModule();
	}

	protected Module getUiModule(String grammar) {
		if(COM_PUPPETLABS_GEPPETTO_MODULE_DSL_MODULE.equals(grammar)) {
			return new com.puppetlabs.geppetto.module.dsl.ui.ModuleUiModule(this);
		}

		throw new IllegalArgumentException(grammar);
	}

	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		INSTANCE = this;
	}

	@Override
	public void stop(BundleContext context) throws Exception {
		injectors.clear();
		INSTANCE = null;
		super.stop(context);
	}

}
