/*
* generated by Xtext
*/
package com.puppetlabs.geppetto.module.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.puppetlabs.geppetto.module.dsl.services.ModuleGrammarAccess;

public class ModuleParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ModuleGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected com.puppetlabs.geppetto.module.dsl.parser.antlr.internal.InternalModuleParser createParser(XtextTokenStream stream) {
		return new com.puppetlabs.geppetto.module.dsl.parser.antlr.internal.InternalModuleParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ModuleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ModuleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
