/*
* generated by Xtext
*/
package com.puppetlabs.geppetto.module.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModuleAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/puppetlabs/geppetto/module/dsl/parser/antlr/internal/InternalModule.tokens");
	}
}
