/*
* generated by Xtext
*/
package com.puppetlabs.geppetto.module.dsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.puppetlabs.geppetto.module.dsl.services.ModuleGrammarAccess;

public class ModuleParser extends AbstractContentAssistParser {
	
	@Inject
	private ModuleGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.puppetlabs.geppetto.module.dsl.ui.contentassist.antlr.internal.InternalModuleParser createParser() {
		com.puppetlabs.geppetto.module.dsl.ui.contentassist.antlr.internal.InternalModuleParser result = new com.puppetlabs.geppetto.module.dsl.ui.contentassist.antlr.internal.InternalModuleParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getMetadataPairAccess().getAlternatives(), "rule__MetadataPair__Alternatives");
					put(grammarAccess.getDependencyPairAccess().getAlternatives(), "rule__DependencyPair__Alternatives");
					put(grammarAccess.getRequirementPairAccess().getAlternatives(), "rule__RequirementPair__Alternatives");
					put(grammarAccess.getOSPairAccess().getAlternatives(), "rule__OSPair__Alternatives");
					put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
					put(grammarAccess.getQ_StringOrKeyAccess().getAlternatives(), "rule__Q_StringOrKey__Alternatives");
					put(grammarAccess.getQ_ReqUnknownKeyAccess().getAlternatives(), "rule__Q_ReqUnknownKey__Alternatives");
					put(grammarAccess.getQ_OsUnknownKeyAccess().getAlternatives(), "rule__Q_OsUnknownKey__Alternatives");
					put(grammarAccess.getBOOLAccess().getAlternatives(), "rule__BOOL__Alternatives");
					put(grammarAccess.getJsonMetadataAccess().getGroup(), "rule__JsonMetadata__Group__0");
					put(grammarAccess.getJsonMetadataAccess().getGroup_2(), "rule__JsonMetadata__Group_2__0");
					put(grammarAccess.getJsonObjectAccess().getGroup(), "rule__JsonObject__Group__0");
					put(grammarAccess.getJsonObjectAccess().getGroup_2(), "rule__JsonObject__Group_2__0");
					put(grammarAccess.getJsonObjectAccess().getGroup_2_1(), "rule__JsonObject__Group_2_1__0");
					put(grammarAccess.getAuthorPairAccess().getGroup(), "rule__AuthorPair__Group__0");
					put(grammarAccess.getDependenciesPairAccess().getGroup(), "rule__DependenciesPair__Group__0");
					put(grammarAccess.getIssuesUrlPairAccess().getGroup(), "rule__IssuesUrlPair__Group__0");
					put(grammarAccess.getLicensePairAccess().getGroup(), "rule__LicensePair__Group__0");
					put(grammarAccess.getNamePairAccess().getGroup(), "rule__NamePair__Group__0");
					put(grammarAccess.getOperatingsystemSupportPairAccess().getGroup(), "rule__OperatingsystemSupportPair__Group__0");
					put(grammarAccess.getProjectPagePairAccess().getGroup(), "rule__ProjectPagePair__Group__0");
					put(grammarAccess.getRequirementsPairAccess().getGroup(), "rule__RequirementsPair__Group__0");
					put(grammarAccess.getSourcePairAccess().getGroup(), "rule__SourcePair__Group__0");
					put(grammarAccess.getSummaryPairAccess().getGroup(), "rule__SummaryPair__Group__0");
					put(grammarAccess.getTagsPairAccess().getGroup(), "rule__TagsPair__Group__0");
					put(grammarAccess.getVersionPairAccess().getGroup(), "rule__VersionPair__Group__0");
					put(grammarAccess.getUnrecognizedMetadataPairAccess().getGroup(), "rule__UnrecognizedMetadataPair__Group__0");
					put(grammarAccess.getStringArrayAccess().getGroup(), "rule__StringArray__Group__0");
					put(grammarAccess.getStringArrayAccess().getGroup_2(), "rule__StringArray__Group_2__0");
					put(grammarAccess.getStringArrayAccess().getGroup_2_1(), "rule__StringArray__Group_2_1__0");
					put(grammarAccess.getDependencyArrayAccess().getGroup(), "rule__DependencyArray__Group__0");
					put(grammarAccess.getDependencyArrayAccess().getGroup_2(), "rule__DependencyArray__Group_2__0");
					put(grammarAccess.getDependencyArrayAccess().getGroup_2_1(), "rule__DependencyArray__Group_2_1__0");
					put(grammarAccess.getJsonDependencyAccess().getGroup(), "rule__JsonDependency__Group__0");
					put(grammarAccess.getJsonDependencyAccess().getGroup_2(), "rule__JsonDependency__Group_2__0");
					put(grammarAccess.getMetadataRefPairAccess().getGroup(), "rule__MetadataRefPair__Group__0");
					put(grammarAccess.getRequirementArrayAccess().getGroup(), "rule__RequirementArray__Group__0");
					put(grammarAccess.getRequirementArrayAccess().getGroup_2(), "rule__RequirementArray__Group_2__0");
					put(grammarAccess.getRequirementArrayAccess().getGroup_2_1(), "rule__RequirementArray__Group_2_1__0");
					put(grammarAccess.getJsonRequirementAccess().getGroup(), "rule__JsonRequirement__Group__0");
					put(grammarAccess.getJsonRequirementAccess().getGroup_2(), "rule__JsonRequirement__Group_2__0");
					put(grammarAccess.getRequirementPairAccess().getGroup_0(), "rule__RequirementPair__Group_0__0");
					put(grammarAccess.getVRPairAccess().getGroup(), "rule__VRPair__Group__0");
					put(grammarAccess.getUnrecognizedRequirementPairAccess().getGroup(), "rule__UnrecognizedRequirementPair__Group__0");
					put(grammarAccess.getTagArrayAccess().getGroup(), "rule__TagArray__Group__0");
					put(grammarAccess.getTagArrayAccess().getGroup_2(), "rule__TagArray__Group_2__0");
					put(grammarAccess.getTagArrayAccess().getGroup_2_1(), "rule__TagArray__Group_2_1__0");
					put(grammarAccess.getOSArrayAccess().getGroup(), "rule__OSArray__Group__0");
					put(grammarAccess.getOSArrayAccess().getGroup_2(), "rule__OSArray__Group_2__0");
					put(grammarAccess.getOSArrayAccess().getGroup_2_1(), "rule__OSArray__Group_2_1__0");
					put(grammarAccess.getJsonOSAccess().getGroup(), "rule__JsonOS__Group__0");
					put(grammarAccess.getJsonOSAccess().getGroup_2(), "rule__JsonOS__Group_2__0");
					put(grammarAccess.getOSPairAccess().getGroup_0(), "rule__OSPair__Group_0__0");
					put(grammarAccess.getOSPairAccess().getGroup_1(), "rule__OSPair__Group_1__0");
					put(grammarAccess.getUnrecognizedOSPairAccess().getGroup(), "rule__UnrecognizedOSPair__Group__0");
					put(grammarAccess.getPairAccess().getGroup(), "rule__Pair__Group__0");
					put(grammarAccess.getJsonArrayAccess().getGroup(), "rule__JsonArray__Group__0");
					put(grammarAccess.getJsonArrayAccess().getGroup_2(), "rule__JsonArray__Group_2__0");
					put(grammarAccess.getJsonArrayAccess().getGroup_2_1(), "rule__JsonArray__Group_2_1__0");
					put(grammarAccess.getJsonMetadataAccess().getPairsAssignment_1(), "rule__JsonMetadata__PairsAssignment_1");
					put(grammarAccess.getJsonMetadataAccess().getPairsAssignment_2_1(), "rule__JsonMetadata__PairsAssignment_2_1");
					put(grammarAccess.getJsonObjectAccess().getPairsAssignment_2_0(), "rule__JsonObject__PairsAssignment_2_0");
					put(grammarAccess.getJsonObjectAccess().getPairsAssignment_2_1_1(), "rule__JsonObject__PairsAssignment_2_1_1");
					put(grammarAccess.getAuthorPairAccess().getNameAssignment_0(), "rule__AuthorPair__NameAssignment_0");
					put(grammarAccess.getAuthorPairAccess().getValueAssignment_2(), "rule__AuthorPair__ValueAssignment_2");
					put(grammarAccess.getDependenciesPairAccess().getNameAssignment_0(), "rule__DependenciesPair__NameAssignment_0");
					put(grammarAccess.getDependenciesPairAccess().getValueAssignment_2(), "rule__DependenciesPair__ValueAssignment_2");
					put(grammarAccess.getIssuesUrlPairAccess().getNameAssignment_0(), "rule__IssuesUrlPair__NameAssignment_0");
					put(grammarAccess.getIssuesUrlPairAccess().getValueAssignment_2(), "rule__IssuesUrlPair__ValueAssignment_2");
					put(grammarAccess.getLicensePairAccess().getNameAssignment_0(), "rule__LicensePair__NameAssignment_0");
					put(grammarAccess.getLicensePairAccess().getValueAssignment_2(), "rule__LicensePair__ValueAssignment_2");
					put(grammarAccess.getNamePairAccess().getNameAssignment_0(), "rule__NamePair__NameAssignment_0");
					put(grammarAccess.getNamePairAccess().getValueAssignment_2(), "rule__NamePair__ValueAssignment_2");
					put(grammarAccess.getOperatingsystemSupportPairAccess().getNameAssignment_0(), "rule__OperatingsystemSupportPair__NameAssignment_0");
					put(grammarAccess.getOperatingsystemSupportPairAccess().getValueAssignment_2(), "rule__OperatingsystemSupportPair__ValueAssignment_2");
					put(grammarAccess.getProjectPagePairAccess().getNameAssignment_0(), "rule__ProjectPagePair__NameAssignment_0");
					put(grammarAccess.getProjectPagePairAccess().getValueAssignment_2(), "rule__ProjectPagePair__ValueAssignment_2");
					put(grammarAccess.getRequirementsPairAccess().getNameAssignment_0(), "rule__RequirementsPair__NameAssignment_0");
					put(grammarAccess.getRequirementsPairAccess().getValueAssignment_2(), "rule__RequirementsPair__ValueAssignment_2");
					put(grammarAccess.getSourcePairAccess().getNameAssignment_0(), "rule__SourcePair__NameAssignment_0");
					put(grammarAccess.getSourcePairAccess().getValueAssignment_2(), "rule__SourcePair__ValueAssignment_2");
					put(grammarAccess.getSummaryPairAccess().getNameAssignment_0(), "rule__SummaryPair__NameAssignment_0");
					put(grammarAccess.getSummaryPairAccess().getValueAssignment_2(), "rule__SummaryPair__ValueAssignment_2");
					put(grammarAccess.getTagsPairAccess().getNameAssignment_0(), "rule__TagsPair__NameAssignment_0");
					put(grammarAccess.getTagsPairAccess().getValueAssignment_2(), "rule__TagsPair__ValueAssignment_2");
					put(grammarAccess.getVersionPairAccess().getNameAssignment_0(), "rule__VersionPair__NameAssignment_0");
					put(grammarAccess.getVersionPairAccess().getValueAssignment_2(), "rule__VersionPair__ValueAssignment_2");
					put(grammarAccess.getUnrecognizedMetadataPairAccess().getNameAssignment_0(), "rule__UnrecognizedMetadataPair__NameAssignment_0");
					put(grammarAccess.getUnrecognizedMetadataPairAccess().getValueAssignment_2(), "rule__UnrecognizedMetadataPair__ValueAssignment_2");
					put(grammarAccess.getStringArrayAccess().getValueAssignment_2_0(), "rule__StringArray__ValueAssignment_2_0");
					put(grammarAccess.getStringArrayAccess().getValueAssignment_2_1_1(), "rule__StringArray__ValueAssignment_2_1_1");
					put(grammarAccess.getDependencyArrayAccess().getValueAssignment_2_0(), "rule__DependencyArray__ValueAssignment_2_0");
					put(grammarAccess.getDependencyArrayAccess().getValueAssignment_2_1_1(), "rule__DependencyArray__ValueAssignment_2_1_1");
					put(grammarAccess.getJsonDependencyAccess().getPairsAssignment_1(), "rule__JsonDependency__PairsAssignment_1");
					put(grammarAccess.getJsonDependencyAccess().getPairsAssignment_2_1(), "rule__JsonDependency__PairsAssignment_2_1");
					put(grammarAccess.getMetadataRefPairAccess().getNameAssignment_0(), "rule__MetadataRefPair__NameAssignment_0");
					put(grammarAccess.getMetadataRefPairAccess().getRefAssignment_2(), "rule__MetadataRefPair__RefAssignment_2");
					put(grammarAccess.getRequirementArrayAccess().getValueAssignment_2_0(), "rule__RequirementArray__ValueAssignment_2_0");
					put(grammarAccess.getRequirementArrayAccess().getValueAssignment_2_1_1(), "rule__RequirementArray__ValueAssignment_2_1_1");
					put(grammarAccess.getJsonRequirementAccess().getPairsAssignment_1(), "rule__JsonRequirement__PairsAssignment_1");
					put(grammarAccess.getJsonRequirementAccess().getPairsAssignment_2_1(), "rule__JsonRequirement__PairsAssignment_2_1");
					put(grammarAccess.getRequirementPairAccess().getNameAssignment_0_0(), "rule__RequirementPair__NameAssignment_0_0");
					put(grammarAccess.getRequirementPairAccess().getValueAssignment_0_2(), "rule__RequirementPair__ValueAssignment_0_2");
					put(grammarAccess.getRequirementNameValueAccess().getValueAssignment(), "rule__RequirementNameValue__ValueAssignment");
					put(grammarAccess.getVRPairAccess().getNameAssignment_0(), "rule__VRPair__NameAssignment_0");
					put(grammarAccess.getVRPairAccess().getValueAssignment_2(), "rule__VRPair__ValueAssignment_2");
					put(grammarAccess.getUnrecognizedRequirementPairAccess().getNameAssignment_0(), "rule__UnrecognizedRequirementPair__NameAssignment_0");
					put(grammarAccess.getUnrecognizedRequirementPairAccess().getValueAssignment_2(), "rule__UnrecognizedRequirementPair__ValueAssignment_2");
					put(grammarAccess.getJsonVersionRangeAccess().getValueAssignment(), "rule__JsonVersionRange__ValueAssignment");
					put(grammarAccess.getJsonModuleNameAccess().getValueAssignment(), "rule__JsonModuleName__ValueAssignment");
					put(grammarAccess.getTagArrayAccess().getValueAssignment_2_0(), "rule__TagArray__ValueAssignment_2_0");
					put(grammarAccess.getTagArrayAccess().getValueAssignment_2_1_1(), "rule__TagArray__ValueAssignment_2_1_1");
					put(grammarAccess.getJsonTagAccess().getValueAssignment(), "rule__JsonTag__ValueAssignment");
					put(grammarAccess.getJsonVersionAccess().getValueAssignment(), "rule__JsonVersion__ValueAssignment");
					put(grammarAccess.getOSArrayAccess().getValueAssignment_2_0(), "rule__OSArray__ValueAssignment_2_0");
					put(grammarAccess.getOSArrayAccess().getValueAssignment_2_1_1(), "rule__OSArray__ValueAssignment_2_1_1");
					put(grammarAccess.getJsonOSAccess().getPairsAssignment_1(), "rule__JsonOS__PairsAssignment_1");
					put(grammarAccess.getJsonOSAccess().getPairsAssignment_2_1(), "rule__JsonOS__PairsAssignment_2_1");
					put(grammarAccess.getOSPairAccess().getNameAssignment_0_0(), "rule__OSPair__NameAssignment_0_0");
					put(grammarAccess.getOSPairAccess().getValueAssignment_0_2(), "rule__OSPair__ValueAssignment_0_2");
					put(grammarAccess.getOSPairAccess().getNameAssignment_1_0(), "rule__OSPair__NameAssignment_1_0");
					put(grammarAccess.getOSPairAccess().getValueAssignment_1_2(), "rule__OSPair__ValueAssignment_1_2");
					put(grammarAccess.getUnrecognizedOSPairAccess().getNameAssignment_0(), "rule__UnrecognizedOSPair__NameAssignment_0");
					put(grammarAccess.getUnrecognizedOSPairAccess().getValueAssignment_2(), "rule__UnrecognizedOSPair__ValueAssignment_2");
					put(grammarAccess.getPairAccess().getNameAssignment_0(), "rule__Pair__NameAssignment_0");
					put(grammarAccess.getPairAccess().getValueAssignment_2(), "rule__Pair__ValueAssignment_2");
					put(grammarAccess.getStringLiteralAccess().getValueAssignment(), "rule__StringLiteral__ValueAssignment");
					put(grammarAccess.getNullValueAccess().getValueAssignment(), "rule__NullValue__ValueAssignment");
					put(grammarAccess.getDoubleLiteralAccess().getValueAssignment(), "rule__DoubleLiteral__ValueAssignment");
					put(grammarAccess.getLongLiteralAccess().getValueAssignment(), "rule__LongLiteral__ValueAssignment");
					put(grammarAccess.getJsonArrayAccess().getValueAssignment_2_0(), "rule__JsonArray__ValueAssignment_2_0");
					put(grammarAccess.getJsonArrayAccess().getValueAssignment_2_1_1(), "rule__JsonArray__ValueAssignment_2_1_1");
					put(grammarAccess.getBooleanLiteralAccess().getValueAssignment(), "rule__BooleanLiteral__ValueAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.puppetlabs.geppetto.module.dsl.ui.contentassist.antlr.internal.InternalModuleParser typedParser = (com.puppetlabs.geppetto.module.dsl.ui.contentassist.antlr.internal.InternalModuleParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS" };
	}
	
	public ModuleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ModuleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
