/*
 * generated by Xtext
 */
package com.puppetlabs.geppetto.module.dsl;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.linking.ILinkingDiagnosticMessageProvider;
import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.resource.IContainer;
import org.eclipse.xtext.resource.IResourceDescription;
import org.eclipse.xtext.resource.IResourceServiceProvider;
import org.eclipse.xtext.resource.containers.StateBasedContainerManager;

import com.google.inject.Binder;
import com.puppetlabs.geppetto.forge.client.GsonModule;
import com.puppetlabs.geppetto.forge.impl.ForgeModule;
import com.puppetlabs.geppetto.injectable.CommonModuleProvider;
import com.puppetlabs.geppetto.module.dsl.linking.ModuleLinkingDiagnosticMessageProvider;
import com.puppetlabs.geppetto.module.dsl.scoping.ModuleQualifiedNameConverter;
import com.puppetlabs.geppetto.module.dsl.scoping.ModuleQualifiedNameProvider;
import com.puppetlabs.geppetto.pp.dsl.FolderDiscriminator;
import com.puppetlabs.geppetto.pp.dsl.IFolderDiscriminator;

public class ModuleRuntimeModule extends AbstractModuleRuntimeModule {
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return ModuleConverters.class;
	}

	public Class<? extends ILinkingDiagnosticMessageProvider> bindILinkingDiagnosticMessageProvider() {
		return ModuleLinkingDiagnosticMessageProvider.class;
	}

	public Class<? extends IFolderDiscriminator> bindIFolderDiscriminator() {
		return FolderDiscriminator.class;
	}

	/**
	 * Binds the resource provide that reacts to "metadata.json" files rather than
	 * just the filename extension
	 */
	public Class<? extends IResourceServiceProvider> bindIResourceServiceProvider() {
		return ModuleResourceServiceProvider.class;
	}

	/**
	 * Metadata names use the '-' as the separator
	 */
	public Class<? extends IQualifiedNameConverter> bindIQualifiedNameConverter() {
		return ModuleQualifiedNameConverter.class;
	}

	public Class<? extends IResourceDescription.Manager> bindIResourceDescriptionManager() {
		return ModuleResourceDescriptionManager.class;
	}

	/**
	 * Name must be provided from a specific JSON entry
	 */
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return ModuleQualifiedNameProvider.class;
	}

	@Override
	public Class<? extends IContainer.Manager> bindIContainer$Manager() {
		return StateBasedContainerManager.class;
	}

	public void configureForge(Binder binder) {
		binder.install(CommonModuleProvider.getCommonModule());
		binder.install(GsonModule.INSTANCE);
		binder.install(new ForgeModule());
	}
}
