/*
 * generated by Xtext
 */
package com.puppetlabs.geppetto.module.dsl.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IFileSystemAccess
import org.eclipse.xtext.generator.IGenerator

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
class ModuleGenerator implements IGenerator {
	override void doGenerate(Resource resource, IFileSystemAccess fsa) {
	}
}
