package com.puppetlabs.geppetto.pp.dsl.ui;

/*
 * generated by Xtext
 */

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;
import com.puppetlabs.geppetto.pp.dsl.ui.internal.PPDSLActivator;
import com.puppetlabs.geppetto.ruby.resource.PptpRubyRuntimeModule;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class RBExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PPDSLActivator.getInstance().getBundle();
	}

	@Override
	protected Injector getInjector() {
		return PPDSLActivator.getInstance().getInjector(PptpRubyRuntimeModule.PPTP_RUBY_LANGUAGE_NAME);
	}

}
